=== curvenote/jats/packages/meca/static/transfer-1.0.dtd
<!-- DOCTYPE manifest PUBLIC â€œ-//MECA//DTD Transfer v1.0//en" "https://meca.zip/transfer-1.0.dtd" -->
<!-- ============================================================= -->
<!-- SPECIAL CHARACTER MODULES -->
<!-- ============================================================= -->
<!-- SPECIAL CHARACTERS DECLARATIONS -->
<!-- Declares any standard XML special character
 entities used in this DTD -->
<!ENTITY % xmlspecchars.ent
 PUBLIC
"-//NLM//DTD JATS (Z39.96) JATS DTD Suite XML Special Characters Module v1.2 20190208//EN"
"JATS-xmlspecchars1.ent" >
<!-- CUSTOM SPECIAL CHARACTERS DECLARATIONS -->
<!-- Declares any custom special character
 entities created for this Suite -->
<!ENTITY % chars.ent PUBLIC
"-//NLM//DTD JATS (Z39.96) JATS DTD Suite Custom Special Characters Module v1.2
20190208//EN"
"JATS-chars1.ent" >
<!ELEMENT transfer (transfer-source, destination, processing-instructions?)>
<!ATTLIST transfer xmlns CDATA #FIXED "https://manuscriptexchange.org/schema/transfer">
<!ATTLIST transfer transfer-version CDATA #REQUIRED>
<!ELEMENT transfer-source (service-provider?, publication, security?)>
<!ELEMENT service-provider (provider-name?, contact?)>
<!ELEMENT provider-name (#PCDATA)>
<!ELEMENT contact (contact-name?, (email|phone)+)>
<!ATTLIST contact contact-role CDATA #IMPLIED>
<!ELEMENT contact-name (surname?, given-names?)>
<!ELEMENT surname (#PCDATA)>
<!ELEMENT given-names (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT publication (publication-title, acronym?, contact?)>
<!ATTLIST publication type CDATA #IMPLIED>
<!ELEMENT publication-title (#PCDATA)>
<!ELEMENT acronym (#PCDATA)>
<!ELEMENT security (authentication-code)>
<!ELEMENT authentication-code (#PCDATA)>
<!ELEMENT destination (service-provider, publication, security?)>
<!-- The processing instructions tag is a placeholder for implementation-specific instructions between
vendors and publishers-->
<!ELEMENT processing-instructions (processing-instruction*, processing-comments?)>
<!ELEMENT processing-instruction (#PCDATA)>
<!ATTLIST processing-instruction processing-sequence CDATA #IMPLIED>
<!ELEMENT processing-comments (#PCDATA)>

=== curvenote/jats/packages/meca/tests/transfer-spec.xml
<!DOCTYPE transfer PUBLIC "-//MECA//DTD Transfer v1.0//en" "https://meca.zip/transfer-1.0.dtd">
<transfer xmlns="https://manuscriptexchange.org/schema/transfer" transfer-version="1.0">
  <transfer-source>
    <service-provider>
      <provider-name>Aries Systems</provider-name>
      <contact>
        <contact-name>
          <surname>Smith</surname>
          <given-names>Mary</given-names>
        </contact-name>
        <email>MarySmith@sample.email</email>
        <phone>444-555-0101</phone>
      </contact>
    </service-provider>
    <publication type="journal">
      <publication-title>The Journal of the American Medical Association</publication-title>
      <acronym>JAMA</acronym>
      <contact>
        <email>MyJournal@ariessys.com</email>
      </contact>
    </publication>
  </transfer-source>
  <destination>
    <service-provider>
      <provider-name>Highwire</provider-name>
      <contact contact-role="Project Manager">
        <contact-name>
          <surname>Rogers</surname>
          <given-names>John</given-names>
        </contact-name>
        <email>jrogers@highwire.com</email>
        <phone>444-555-1212</phone>
      </contact>
    </service-provider>
    <publication type="preprint-server">
      <publication-title>bioRxiv</publication-title>
      <acronym>bioRxiv</acronym>
      <contact contact-role="Managing Editor">
        <contact-name>
          <surname>Rogers</surname>
          <given-names>Sally</given-names>
        </contact-name>
        <email>srogers@bioarxiv.com</email>
        <phone>301-555-1212</phone>
      </contact>
    </publication>
    <security>
      <authentication-code>abdasa-13123-abae</authentication-code>
    </security>
  </destination>
  <processing-instructions>
    <processing-instruction processing-sequence="1"
    >Verify XML First</processing-instruction>
    <processing-instruction processing-sequence="2"
    >Load XML</processing-instruction>
    <processing-comments>Free form comments</processing-comments>
  </processing-instructions>
</transfer>
